require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
  DisplayCopNames: true

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'Gemfile'
    - 'config/**/*'
    - 'spec/**/*_spec.rb'
    - 'lib/tasks/*'

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
